# -*- coding: utf-8 -*-
"""Copy of country-discount-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPtBV3SV3TcOep7xF_JF1VcRZgNf1ZBV
"""

name = input("Enter your name: \n")
age = int(input("Enter your age: \n"))
country = input("Enter your country: \n").lower()

if country == "egypt":
    if age < 18:
        print("Your discount is: 50%")
    else:
        print("Your discount is: 15%")

elif country == "france":
    print("Your discount is: 30%")

elif country == "syria":
    print("Your discount is: 40%")

elif country == "england":
    print("Your discount is: 10%")

else:
    print("No discount!")