# -*- coding: utf-8 -*-
"""pin code matcher🔒

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UO1m73Ie4eICzz6-0tzepNQKFj8jiho8
"""

import random
pin_code=random.randint(1000,9999)
user_input=int(input("enter a 4 digits pin code :"))

#i have to make sure that the user entered 4 digits not more and not less so:
#and don't forget that the input is (int) and len not gonna accept it so we should convert it to (str)

#if len(str(user_input))>4 or len(str(user_input))<4:
if user_input!=4:
 print("please enter 4 digits :")

elif user_input==pin_code:
  print("success!pin code matched ")
else:
  print("pin code not matched! ")
  print(f"the right pin is: {pin_code} ")